development:
  enable_star: 1
  mem_limit: 128M
  min_infix_len: 1
  # The following is needed to make sure course codes are easily searchable
  blend_chars: +, &, ., -
  # For better char support
  # charset_table: "0..9, A..Z->a..z, _, a..z, U+410..U+42F->U+430..U+44F, U+430..U+44F"
test:
  enable_star: 1
  min_infix_len: 1
  charset_table: "0..9, A..Z->a..z, _, a..z, U+410..U+42F->U+430..U+44F, U+430..U+44F"
production:
  enable_star: 1
  min_infix_len: 1
  charset_table: "0..9, A..Z->a..z, _, a..z, U+410..U+42F->U+430..U+44F, U+430..U+44F"
