development:
  enable_star: 1
  mem_limit: 128M
  min_infix_len: 4
  # The following is needed to make sure course codes are easily searchable
  blend_chars: +, &, ., -
  # For better char support
  charset_type: utf-8
  charset_table: "0..9, A..Z->a..z, _, a..z, U+410..U+42F->U+430..U+44F, U+430..U+44F"
test:
  #
production:
  enable_star: 1
  mem_limit: 128M
  min_infix_len: 4
  blend_chars: +, &, ., -
  charset_type: utf-8
  charset_table: "0..9, A..Z->a..z, _, a..z, U+410..U+42F->U+430..U+44F, U+430..U+44F"